version: '3'

services:
  auth_service:
    image: msa-notification-system
    volumes:
      - .:/usr/src/app
    expose:
      - 4002
    command: node auth-service/server.js
    depends_on:
      - mongodb

  notification_service:
    image: msa-notification-system
    volumes:
      - .:/usr/src/app
    expose:
      - 4000
    environment:
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://localhost:9092
    command: node notification-service/server.js
    depends_on:
      - mongodb
      - kafka
  
  real_time_service:
    image: msa-notification-system
    volumes:
      - .:/usr/src/app
    expose:
      - 4001
    command: node real-time-service/server.js
    depends_on:
      - kafka

  mongodb:
    image: mongo:latest
    expose:
      - 27017
    environment:
      - MONGO_INITDB_DATABASE=notification_system
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - './data:/data/db'

  # unsure if you must mount, maybe just expose as only it will avaible within the system.
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    expose:
      - 2181

  kafka:
    image: confluentinc/cp-kafka:6.2.1
    container_name: kafka
    expose:
      - 9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - auth_service
      - notification_service
